CREATE TABLE NEWS(
    ID NUMBER(38) NOT NULL PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    CONTENT CLOB,
    PUBLISHED_DATE DATE,
    AUTHOR VARCHAR(50)
);
CREATE SEQUENCE NEWS_SEQUENCE START WITH 1 INCREMENT BY 1 NOMAXVALUE;